import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "About us",
  description: "Generated by create next app",
};

const AboutUs = () => {
  return (
    <div>About Us</div>
  )
}

export default AboutUs