import "../../styles/global.css"
import type { Metadata } from "next";
import Link from "next/link";
import Navigation from "../../components/navigation";

export const metadata: Metadata = {
  title: {
    template: "%s | Next Movies",
    default: "Next",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navigation/>
        </header>
        {children}
      </body>
    </html>
  );
}
